### ISSUE TITLE
Jumping monsters do not disappear at the end of spawn time

### ISSUE THREAD

**Issue by na-ji** [cecpk/OSM-Rocketmap#45]
## Expected Behavior

At the end of a spawn time, every monsters should disappear from the map.

## Current Behavior

Currently, jumping monster does not disappear. 

## Steps to Reproduce (for bugs)

1. Having jumping monster
2. Waiting end of spawn time

## Your Environment

* Version used: latest
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): desktop

**Comment by cecpk** [comment]
fixed
