### ISSUE TITLE
Regular non-IV mon doesn't auto update after IV scan

### ISSUE THREAD

**Issue by JimBim89** [cecpk/OSM-Rocketmap#47]
## Expected Behavior
Update mon tooltip / notification without having to reload site.

## Current Behavior
Rocketmap needs to be reloaded to display rescanned mons.

## Steps to Reproduce (for bugs)

1. Have a non-iv mon in db from MAD
2. Scan mon via mon_mitm or iv_mitm
3. Mouse over mon (no update visible)
4. Reload -> now IV will show correctly

**Comment by daangroot** [comment]
This has been fixed by: https://github.com/cecpk/OSM-Rocketmap/pull/103
