### ISSUE TITLE
Custom.js causes CRITICAL error pm startup

### ISSUE THREAD

**Issue by 0xC1A551C** [cecpk/OSM-Rocketmap#58]
## Expected Behavior
runserver.py should run normally and detect custom.js

## Current Behavior
runserver.py detects a critical error.

```
root@vps227991:/home/rocketmap/OSM-Rocketmap# python3 runserver.py 
 [06-11 22:02:30] [      MainThread] [     runserver] [CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server.

```
## Steps to Reproduce (for bugs)

1. Copy custom.js.example from static/js to custom.js in static/js
2. Run runserver.py
3. Observe
4. Removing custom.js fixes it

## Context
Trying to use custom.js to disable the search marker

## Your Environment
* Version used: Development 
* Environment name and version (e.g. Python 3.5): Python 3
* Operating System and version (desktop or mobile): desktop debian 9

**Comment by sn0opy** [comment]
Double check the error. It even tells you what you have to do to solve the problem.
