### ISSUE TITLE
Raid timer jumps back and forward between 00m00s and actual time

### ISSUE THREAD

**Issue by daangroot** [cecpk/OSM-Rocketmap#77]
This is most likely caused by the fact that gym markers and gym labels are constantly being updated, even when a gym doesn't change.
Hence a fix would be to only update the markers and labels when a gym changes.

**Comment by JimBim89** [comment]
Easy fix would be to remove the default time I guess? Any downsides?

**Comment by daangroot** [comment]
This has been fixed by: https://github.com/cecpk/OSM-Rocketmap/pull/97.
