### ISSUE TITLE
OSM-RM creates broken DB schema.

### ISSUE THREAD

**Issue by sebastienvercammen** [cecpk/OSM-Rocketmap#94]
## Expected Behavior
OSM-RM should generate a DB schema that can fit the data received from GMO calls (e.g. MAD).

## Current Behavior
OSM-RM links to latest peewee in [requirements.txt](https://github.com/cecpk/OSM-Rocketmap/blob/develop/requirements.txt#L11), which changes the old `db_field` attribute to `field_type`, as published [in their docs](http://docs.peewee-orm.com/en/latest/peewee/changes.html):

![image](https://user-images.githubusercontent.com/4874269/63182339-ab948780-c052-11e9-8125-7d91eed5407c.png)

Since v3.0. Latest is `peewee` v3.10.

But in the OSM-RM code, `db_field` is still used. Since this code no longer works, the fields are defined as signed `bigint` instead of `unsigned`.

https://github.com/cecpk/OSM-Rocketmap/blob/490b6e5eb9640f4ee21aaf71a85a2acfe2b8e96a/pogom/models.py#L68-L69

In the original RocketMap `peewee` was pinned to `2.8.1` since that was the most recent version at the time, so this is probably a copy/paste mistake.

The `signed bigint` is too small to fit all data, causing this error in MAD:
![image](https://user-images.githubusercontent.com/4874269/63182613-442b0780-c053-11e9-8a53-22d48533acf4.png)

## Solution
Change `db_field` to `field_type` and run the following migration schema:
```
ALTER TABLE spawnpoint MODIFY id bigint(20) unsigned NOT NULL;
ALTER TABLE scannedlocation MODIFY cellid bigint(20) unsigned NOT NULL;
ALTER TABLE pokemon MODIFY encounter_id bigint(20) unsigned NOT NULL;
ALTER TABLE pokemon MODIFY spawnpoint_id bigint(20) unsigned NOT NULL;
```

**Note:** I didn't check for more occurrences of unsigned bigints besides CTRL+F in [models.py](https://github.com/cecpk/OSM-Rocketmap/blob/develop/pogom/models.py#L68-L69).

**Comment by daangroot** [comment]
Good catch, thanks! This has been fixed by https://github.com/cecpk/OSM-Rocketmap/commit/6b23dda73de38e35ee73f7dc4cc13d5ceb4430b1 and https://github.com/cecpk/OSM-Rocketmap/commit/b68720b7ab8e3f5c912934939aa265f67afd8073
